class Py2SoError(Exception):
    pass
